### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by biscayne74** [soundshed/soundshed-app#13]
Working well for me on Win OS , For some reason I cant find the installed software. Every time I use it I launch the EXE file and install? I'm sure that I'm missing something. Thanks!

**Comment by webprofusion-chrisc** [comment]
Thanks, no it's the same for me, the installer fails to create the desktop shortcuts. My workaround is to launch the app then Right Click - pin to taskbar.

**Comment by webprofusion-chrisc** [comment]
This should be fixed now in v1.0.21.

For posterity, the issue was the Squirrel installer `--createShortcut` was erroring with an invalid path and it turned out that it was automatically being fed the author field from the `package.json`, which was set to `https://soundshed.com`, Squirrel then tried to make that a file path which was of course invalid.
