### ISSUE TITLE
Max tone name length

### ISSUE THREAD

**Issue by fefillo** [soundshed/soundshed-app#28]
Hi, I just ran into a problem after renaming a bunch of my tones some would not work. When you select them in the "My Tones" area, and then go to Amp, the Amp controls show up blank and there's no effects applied. 

After playing around with the program, I realized that if I renamed the tones back to their original (or just shorter names), the tones would work again.

I tried to find the limit but it was not consistent. 
I named a tone 12345678901234567890 (20 characters) and it did not work, but 1234567890123456789 (19) does work fine. 
I have another tone named "PF - Comfortably Numb Solo 1" (28 characters if you count spaces) that works fine. I tried renaming to add characters and it still works at 29, but stops working at 30.

**Comment by webprofusion-chrisc** [comment]
Thanks, this is a limitation of the spark itself, we should add some validation to stop you entering long titles.

**Comment by jxw** [comment]
Based on the protocol spec document by Paul Hamshere ( https://github.com/paulhamsh/Spark-Bluetooth-Message-Format ), preset names can only be 31 characters max.  On top of that, I've seen odd behavior where Soundshed was not able to parse preset info when the preset name was short (only 4 characters long (!) I worked around it by changing the name to 7 characters).  I think that _might_ be due to how the preset data is broken up into chunks and Soundshed not properly handling cases where the last chunk is particularly short.  Chris and I are working on updating the communications code, so if we get it right, that should also fix this (the 31 character limit still applies, of course).

Note that preset data length is not just a function of preset name - the names of the effects and amps uses are also variable and contribute to the overall length of the preset data, so it's not as simple as saying preset names of a particular length don't work.  As an experiment, try changing a selected effect or amp to another one whose name is a different length and saving the preset with the preset name that didn't work before - you might find that it suddenly works.
